ARG BUILD_ARCH=x64

#FROM forumi0721debian${BUILD_ARCH}build/debian-${BUILD_ARCH}-qemu-static-builder:latest as qemu

FROM forumi0721/alpine-${BUILD_ARCH}-base:latest as builder

LABEL maintainer="forumi0721@gmail.com"

ENV TARGET_ARCH=x64xenial

COPY local/. /usr/local/

#COPY --from=qemu /output/qemu-static /usr/local/bin

RUN ["docker-init"]



FROM scratch

LABEL maintainer="forumi0721@gmail.com"

COPY --from=builder /build/dist/dist-ubuntu-x64-xenial /

#RUN ["docker-build-start"]

RUN ["docker-init"]

#RUN ["docker-build-end"]

ENTRYPOINT ["docker-run"]

