ARG BUILDER=forumi0721/alpine-base:latest

FROM ${BUILDER} as builder

LABEL maintainer="forumi0721@gmail.com"

ENV TARGET_ARCH=x64bionic

COPY local/. /usr/local/

RUN ["docker-init"]



FROM scratch

LABEL maintainer="forumi0721@gmail.com"

COPY --from=builder /build/dist/dist-ubuntu-x64-bionic /

#RUN ["docker-build-start"]

RUN ["docker-init"]

#RUN ["docker-build-end"]

ENTRYPOINT ["docker-run"]

