ARG BUILD_ARCH=x64

FROM forumi0721/alpine-${BUILD_ARCH}-base:latest as builder

LABEL maintainer="forumi0721@gmail.com"

ENV TARGET_ARCH=aarch64

COPY local/. /usr/local/

RUN ["docker-init"]



FROM scratch

COPY --from=builder /build/dist/dist-ubuntu-aarch64 /

RUN ["docker-build-start"]

RUN ["docker-init"]

RUN ["docker-build-end"]

ENTRYPOINT ["docker-run"]

