#!/bin/bash

set -euo pipefail

case "$DOCKER_TAG" in
	amd64) platform=linux/amd64 ;;
	arm64) platform=linux/arm64 ;;
	*)
		echo "Unsupported tag: $DOCKER_TAG" >&2
		exit 1
		;;
esac

args=()

if [ "${BUILD_NO_CACHE:-false}" = "true" ]; then
	args+=(--no-cache)
fi

docker build \
	--platform "$platform" \
	"${args[@]}" \
	--pull \
	-f "$DOCKERFILE_PATH" \
	-t "$IMAGE_NAME" \
	.
