#!/bin/bash

set -euo pipefail

case "$DOCKER_TAG" in
	amd64) platform=linux/amd64 ;;
	arm64) platform=linux/arm64 ;;
	*)
		echo "Unsupported tag: $DOCKER_TAG" >&2
		exit 1
		;;
esac

docker build \
	--platform "$platform" \
	-f "$DOCKERFILE_PATH" \
	-t "$IMAGE_NAME" \
	.
