#!/bin/bash

if [ -e multiarch-manifest.yaml ]; then
	curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64
	chmod +x manifest-tool

	./manifest-tool push from-spec multiarch-manifest.yaml
fi
